name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-v2:
    name: Build v2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '^1.21', 'oldstable', 'stable' ]
    steps:
    - uses: extractions/setup-just@v1
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@v4
    - name: Build
      working-directory: v2
      run: |
        just build lint test
      env:
        GOPATH: /home/runner/work/go
  build-v1:
    name: Build v1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '^1.14', 'oldstable', 'stable' ]
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@v4
    - name: Build
      run: |
        mkdir -p $GOPATH/bin
        echo 'export PATH=$PATH:$GOPATH/bin' > runme.sh
        echo 'make tools build lint test' >> runme.sh
        chmod +x runme.sh
        ./runme.sh
      env:
        GOPATH: /home/runner/work/go

