name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '^1.14', 'oldstable', 'stable' ]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Debug
      run: |
        pwd
        echo ${HOME}
        echo ${GITHUB_WORKSPACE}
        echo ${GOPATH}
        echo ${GOROOT}
      env:
        GOPATH: /home/runner/work/go

    - name: Build
      run: |
        mkdir -p $GOPATH/bin
        echo 'export PATH=$PATH:$GOPATH/bin' > runme.sh
        echo 'make tools all' >> runme.sh
        chmod +x runme.sh
        ./runme.sh
      env:
        GOPATH: /home/runner/work/go

