name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint-v1:
    name: Lint v1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - uses: golangci/golangci-lint-action@v6
  lint-v2:
    name: Lint v2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - uses: golangci/golangci-lint-action@v6
      with:
        working-directory: v2
  build-v2:
    name: Build v2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '^1.21', 'oldstable', 'stable' ]
    steps:
    - uses: extractions/setup-just@v1
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@v4
    - name: Build
      working-directory: v2
      run: |
        just build test
      env:
        GOPATH: /home/runner/work/go
  build-v1:
    name: Build v1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '^1.14', 'oldstable', 'stable' ]
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@v4
    - name: Build
      run: make build test

